#!/usr/bin/env python3
"""
Parse raw benchmark CSVs from run_scalability.sh and produce data.csv
in the format expected by plot_scalability.py.

Usage: python summarize_scalability.py RAW_DIR [--out PATH]
  RAW_DIR : directory containing raw_1threads.csv, raw_2threads.csv, etc.
  --out   : output path for data.csv (default: data.csv next to this script)
"""

import argparse
from pathlib import Path

import numpy as np
import pandas as pd
import scipy.stats as st

LAYER_PARAMS = [
    (1, "1 32 112 112 64 3 3 1 1 1 1 1 1 1 1 1 0 0"),
    (2, "1 64 56 56 64 3 3 1 1 1 1 1 1 1 1 1 0 0"),
    (3, "1 224 7 7 224 3 3 1 1 1 1 1 1 1 1 1 0 0"),
    (4, "1 320 14 14 320 2 2 0 0 0 0 2 2 1 1 1 0 1"),
    (5, "1 384 14 14 384 3 3 1 1 1 1 1 1 1 1 384 0 1"),
    (6, "1 960 33 33 256 3 3 12 12 12 12 1 1 12 12 1 0 0"),
]
PARAMS_TO_LAYER = {p: n for n, p in LAYER_PARAMS}

# Map benchmark method names (from executable output) to CSV column names.
# Verify these match the names in your build by checking the raw CSV "name" column.
METHOD_MAP = {
    "Im2col": "im2col",
    "LibTorch": "libtorch",
    "LibTorch_ZeroCopy2D_no_transpose_HWIO": "lt_zconv",
    "ZeroCopy_no_transpose_mkl_jit": "zconv",
}

CORES = [1, 2, 4, 8]

HEADER_COMMENT = """\
# Scaling speedup relative to single-core execution for layers from Table perf-layers.
# Generated by summarize_scalability.py from raw benchmark CSVs.
# Layer mapping (batch=1):
#   Layer 1: IC=32,  IH=112, IW=112, OC=64,  FH=FW=3, PH=PW=1, SH=SW=1, DH=DW=1, GR=1
#   Layer 2: IC=64,  IH=56,  IW=56,  OC=64,  FH=FW=3, PH=PW=1, SH=SW=1, DH=DW=1, GR=1
#   Layer 3: IC=224, IH=7,   IW=7,   OC=224, FH=FW=3, PH=PW=1, SH=SW=1, DH=DW=1, GR=1
#   Layer 4: IC=320, IH=14,  IW=14,  OC=320, FH=FW=2, PH=PW=0, SH=SW=2, DH=DW=1, GR=1  (strided)
#   Layer 5: IC=384, IH=14,  IW=14,  OC=384, FH=FW=3, PH=PW=1, SH=SW=1, DH=DW=1, GR=384 (depthwise)
#   Layer 6: IC=960, IH=33,  IW=33,  OC=256, FH=FW=3, PH=12,   SH=SW=1, DH=DW=12, GR=1  (dilated)
"""


def read_raw(path: Path) -> pd.DataFrame:
    df = pd.read_csv(path, header=0, index_col=False, dtype={"error_occurred": "boolean"})
    df["error_occurred"] = df["error_occurred"].fillna(False)
    df = df[~df["error_occurred"]]
    df[["method", "params"]] = df["name"].str.split(" ", n=1, expand=True)
    # benchmark_runner appends "/repeats" to some names; strip it
    df["params"] = df["params"].str.split("/", n=1).str[0].str.strip()
    return df[df["method"].isin(METHOD_MAP)].copy()


def aggregate(df: pd.DataFrame) -> pd.DataFrame:
    agg = df.groupby(["method", "params"])["real_time"].agg(["mean", "sem", "count"]).reset_index()
    ci = st.norm.interval(0.95, loc=agg["mean"], scale=agg["sem"].clip(lower=1e-12))
    agg["ci95"] = (ci[1] - ci[0]) / 2
    return agg


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("raw_dir", type=Path, help="Directory with raw_Nthreads.csv files")
    parser.add_argument("--out", type=Path, default=None, help="Output path for data.csv")
    args = parser.parse_args()

    raw_dir = args.raw_dir
    out_path = args.out or (Path(__file__).parent / "data.csv")

    # Read and aggregate per core count
    agg_by_cores: dict[int, pd.DataFrame] = {}
    for n in CORES:
        path = raw_dir / f"raw_{n}threads.csv"
        if not path.exists():
            print(f"Warning: {path} not found — skipping {n} cores.")
            continue
        agg_by_cores[n] = aggregate(read_raw(path))

    if 1 not in agg_by_cores:
        raise SystemExit("Error: raw_1threads.csv is required as the baseline.")

    baseline = agg_by_cores[1].set_index(["method", "params"])["mean"]
    baseline_ci = agg_by_cores[1].set_index(["method", "params"])["ci95"]

    rows = []
    non_sig = []
    for n, df in sorted(agg_by_cores.items()):
        for _, row in df.iterrows():
            method_raw = row["method"]
            params = row["params"]
            col = METHOD_MAP[method_raw]
            layer = PARAMS_TO_LAYER.get(params)
            if layer is None:
                print(f"Warning: unrecognized params, skipping: {params!r}")
                continue
            base = baseline.get((method_raw, params))
            bci = baseline_ci.get((method_raw, params))
            if base is None or base == 0:
                print(f"Warning: missing baseline for {method_raw} / layer {layer}")
                continue
            speedup = round(base / row["mean"], 2)
            if n == 1:
                # Baseline is its own reference; speedup = 1.0 by definition.
                sig = True
            else:
                # Error propagation for ratio of two independent measurements.
                rel_err = np.sqrt((bci / base) ** 2 + (row["ci95"] / row["mean"]) ** 2)
                speedup_ci = speedup * rel_err
                sig = (speedup - speedup_ci) > 1.0 or (speedup + speedup_ci) < 1.0
                if not sig:
                    non_sig.append(
                        {
                            "cores": n,
                            "layer": layer,
                            "method": col,
                            "speedup": speedup,
                            "ci95": round(speedup_ci, 3),
                        }
                    )
            rows.append({"cores": n, "layer": layer, "method": col, "speedup": speedup})

    if not rows:
        raise SystemExit("No data produced. Check method names in raw CSVs match METHOD_MAP.")

    df_long = pd.DataFrame(rows)
    df_wide = (
        df_long.pivot_table(index=["cores", "layer"], columns="method", values="speedup")
        .reset_index()
        .sort_values(["layer", "cores"])
        .reset_index(drop=True)
    )
    df_wide.columns.name = None

    # Enforce column order (subset to what is present)
    want = ["cores", "layer", "im2col", "libtorch", "lt_zconv", "zconv"]
    df_wide = df_wide[[c for c in want if c in df_wide.columns]]

    with open(out_path, "w") as f:
        f.write(HEADER_COMMENT)
        df_wide.to_csv(f, index=False)

    print(f"Saved: {out_path}")
    print(df_wide.to_string(index=False))

    total_non_baseline = sum(len(agg_by_cores[n]) for n in agg_by_cores if n > 1)
    if non_sig:
        print(
            f"\n95% CI significance check ({len(non_sig)}/{total_non_baseline} speedups NOT significant):"
        )
        for r in non_sig:
            print(
                f"  Layer {r['layer']}, {r['method']:10s}, {r['cores']}c: "
                f"speedup={r['speedup']:.2f} (CI lower bound ≤ 1.0)"
            )
    else:
        print(
            f"\nAll {total_non_baseline} speedups at N>1 cores are statistically significant "
            f"(95% CI lower bound > 1.0)."
        )


if __name__ == "__main__":
    main()
